/**
 * API Test: Scheduled Jobs — CRUD Operations
 *
 * Maps to TestRail: "Agentic > Scheduled Jobs > API > CRUD"
 *
 * IMPORTANT: Every test that CREATEs a resource MUST call cleanup.track()
 * so the resource is deleted after the test, regardless of pass/fail.
 *
 * Type: Regression | Priority: P1 | Tags: @destructive
 */
import { test, expect } from '../../../src/fixtures/test-fixtures';
import { getAuthHeaders } from '../../../src/helpers/auth.helper';
import { loadEnvConfig } from '../../../src/config/env.config';

const { apiBaseURL: API_BASE } = loadEnvConfig();

/** Minimal valid payload for creating a scheduled job. */
function buildCreatePayload(nameSuffix: string) {
  return {
    name: `QA-AutoCleanup-${nameSuffix}-${Date.now()}`,
    description: 'Auto-generated by QA test — will be deleted after test',
    step: {
      trigger: {
        iCalendarDefinition: 'DTSTART:20260401T060000Z\nRRULE:BYHOUR=6;BYMINUTE=0;FREQ=DAILY',
      },
      process: {
        endpoint: 'https://example.com/qa-noop',
        apiKey: 'qa-test-key',
        timeoutSeconds: 30,
      },
      action: [
        {
          type: 'HOME_PAGE',
          schedule: { mode: 'IMMEDIATE' },
        },
      ],
    },
    audience: { users: [], groups: [] },
  };
}

test.describe('Scheduled Jobs — CRUD API', { tag: ['@api', '@scheduled-jobs', '@destructive'] }, () => {

  test('TC-API-CRUD-001: POST creates a job, cleanup deletes it',
    { tag: ['@regression', '@P1'] },
    async ({ request, cleanup }) => {
    const payload = buildCreatePayload('Create');

    // --- CREATE ---
    const createRes = await request.post(`${API_BASE}/v1/scheduled-jobs`, {
      headers: getAuthHeaders(),
      data: payload,
    });

    // If endpoint not available, skip gracefully
    if (createRes.status() === 404) {
      test.skip(true, 'POST /v1/scheduled-jobs endpoint not available');
      return;
    }

    expect(createRes.status()).toBe(201);
    const body = await createRes.json();
    const jobId = body.data?.id || body.id;
    expect(jobId).toBeTruthy();

    // ★ Register for auto-cleanup — runs after test regardless of pass/fail
    cleanup.track('scheduled-job', jobId);

    // --- VERIFY it exists ---
    const getRes = await request.get(`${API_BASE}/v1/scheduled-jobs/${jobId}`, {
      headers: getAuthHeaders(),
    });
    expect(getRes.status()).toBe(200);
    const getBody = await getRes.json();
    const fetched = getBody.data || getBody;
    expect(fetched.name).toBe(payload.name);
  });

  test('TC-API-CRUD-002: PUT updates a created job',
    { tag: ['@regression', '@P1'] },
    async ({ request, cleanup }) => {
    // --- CREATE ---
    const payload = buildCreatePayload('Update');
    const createRes = await request.post(`${API_BASE}/v1/scheduled-jobs`, {
      headers: getAuthHeaders(),
      data: payload,
    });

    if (createRes.status() === 404) {
      test.skip(true, 'POST /v1/scheduled-jobs endpoint not available');
      return;
    }

    expect(createRes.status()).toBe(201);
    const createBody = await createRes.json();
    const created = createBody.data || createBody;
    const jobId = created.id;
    cleanup.track('scheduled-job', jobId);

    // --- UPDATE (send full payload with changed name) ---
    const updatedName = `QA-Updated-${Date.now()}`;
    const updatePayload = { ...payload, name: updatedName };
    const updateRes = await request.put(`${API_BASE}/v1/scheduled-jobs/${jobId}`, {
      headers: getAuthHeaders(),
      data: updatePayload,
    });
    expect([200, 204]).toContain(updateRes.status());
  });
});
